name: Force update in pkg.go.dev

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Defer time for action
        uses: jakejarvis/wait-action@master
        with:
          time: '15s'
      - name: Update pkg.go.dev
        uses: andrewslotin/go-proxy-pull-action@master

        
